# Generated by Django 2.2.7 on 2019-11-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('subtitle', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('date_published', models.DateField()),
                ('images', models.CharField(max_length=200)),
                ('story', models.CharField(max_length=50)),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='blogs.Tag')),
            ],
        ),
    ]
