# Generated by Django 2.2.7 on 2019-11-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20191119_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='story',
            field=models.TextField(max_length=10000),
        ),
    ]
